# Generated by Django 3.0.8 on 2020-08-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20200824_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=280, null=True),
        ),
    ]
